### ISSUE TITLE
Schema introspection

### ISSUE THREAD

**Issue by vrde** [divad1196/odoo_graphql#10]
:wave: David, thanks for creating this integration for odoo, I'm testing it right now on Odoo 16 without hiccups.

I saw you started a branch already to work on schema introspection: https://github.com/divad1196/odoo_graphql/compare/14.0...14.0+introspection

I was wondering if you have any plan to continue the work you started for the introspection and if you need help in testing it.

**Comment by divad1196** [comment]
@vrde Hi,

Thank you for the proposition.
Yes I will carry on the development, I am just short on time to implement it for the moment and the next 2 weeks.

This does not take time to write the code, my current concern is the design, performance and security of it. Especially, the introspection should be available to only authenticated users (internal and portal) with a specific group.
For this reason I feel more confortable working on it myself.

I cannot give a release date sadly. I should be able to have it working in 1-2 months.

If this is too long for you to wait:
- feel free to implement your version for yourself first
- submit it for PR if you want, I would review it and make a feedback if needed.
  Note that this is not granted that I would accept the PR, even if it works, depending on the issues found.

Thank you for your interest and understanding.

**Comment by vrde** [comment]
Thank you for your prompt reply. I also noticed that there is an endpoint called `graphql/schema`:

https://github.com/divad1196/odoo_graphql/blob/a6845cf8ea238de9a97c137dba1634daa7e67e07/odoo_graphql/controllers/graphql.py#L21-L28

Having introspection and a graphql playground would be ideal, but that endpoint is of great help for now :rocket:

**Comment by divad1196** [comment]
@vrde  Yes, this endpoint just provides a file which is not that great but provides some information that may be injected in some tools.

For the current state of the introspection + embedded graphiQL, the graphiQL interface is integrated and working, the beginning of the translation to ir.module.module/ir.module.field is done. This shouldn't take long to finish the project once I have time to start.

**Comment by divad1196** [comment]
@vrde The feature is done and available on the store.
More information are provided in the module's `readme`  (e,.g Feature not active by default: performance and security).
This feature should only be used for development purpose.

Let me know if you see any issue that I missed (just respond here, I will re-open the issue if needed).
