### ISSUE TITLE
Requests with application/json header are rejected

### ISSUE THREAD

**Issue by TVerberne** [divad1196/odoo_graphql#14]
According to the README.md:35 of plugin version 15 the content-type header with value application/graphql is not required.
When testing in postman the odoo graphql seems to working fine when using the graphql content type but using the general application/json content-type for graphql requests i receive this error in the Odoo console:

`werkzeug.exceptions.BadRequest: 400 Bad Request: <function GraphQL.graphql at 0x7fd34af1ab80>, /graphql: Function declared as capable of handling request of type 'http' but called with a request of type 'json'`

**And this as api response:**

`{
    "jsonrpc": "2.0",
    "id": null,
    "error": {
        "code": 200,
        "message": "Odoo Server Error",
        "data": {
            "name": "werkzeug.exceptions.BadRequest",
            "debug": "Traceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py\", line 237, in _dispatch\n    result = request.dispatch()\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 687, in dispatch\n    result = self._call_function(**self.params)\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 327, in _call_function\n    raise werkzeug.exceptions.BadRequest(msg % params)\nException\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 643, in _handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 301, in _handle_exception\n    raise exception.with_traceback(None) from new_cause\nwerkzeug.exceptions.BadRequest: 400 Bad Request: <function GraphQL.graphql at 0x7fd34af1ab80>, /graphql: Function declared as capable of handling request of type 'http' but called with a request of type 'json'\n",
            "message": "400 Bad Request: <function GraphQL.graphql at 0x7fd34af1ab80>, /graphql: Function declared as capable of handling request of type 'http' but called with a request of type 'json'",
            "arguments": [],
            "context": {}
        }
    }
}`

Normaly using the graphql content-type would be the fastest solution but in this case I am not able to do that because of GraphQL client restrictions that are being used in the middleware project. And according to the readme this should still work.

**Comment by divad1196** [comment]
@TVerberne Odoo consider everything that comes with header application/json has being jsonrpc protocol.

There is nothing I can do for that that wouldn't completely break Odoo (or I need to add an exception to the current handler which needs code injection, meaning I also need to check if the module is installed or not, ... at this point, a rewrite of the header on the reverse-proxy would be a lot better if you absolutely need this header to be application/json).
This is a very basic and common knowledge on how Odoo's routing work and I assume any Odoo developer is aware of that.


This is why I gave examples and didn't try to go in details. I wanted to add an handler sepcificaly for application/graphql but:
1. To be correct, the body for this content-type needs to be only graphal query and not json (meaning you cannot pass variables, ...)
2. This is a lot of work that conflicts with Odoo for no gain.


So just follows the exemples provided. You can use any content-type you want, just not json.
Have a nice day.

**Comment by TVerberne** [comment]
@divad1196 Hi, I managed to successfully create a middleware application that connects to Odoo via this plugin. Now I am working on a scenario where a delete mutation is needed and I am trying to understand how this works in general GraphQL but I don't get it to work yet. I checked the examples page & folder and I understand the mutation for creating and updating but not deleting.

Could you please provide me with a mutation query example to delete an Odoo entity (based on id for example)?
Thank you

**Comment by divad1196** [comment]
@TVerberne deletion is currently not supported.


---

First, I was not really satisfied with allowing create/write and I would prefere using classic RPC for this kind of operations, BUT the advantage of doing it in graphql is that you can retrieve the data before it deleted.

This is the only advantage of using graphql for that for the syntax is really unconvenient

Using the domain to differentiate between create/write was enough, but to integrate deletion I would need to pass another marker, like a directive or an argument, or maybe even requiring the user to specify explicitly if this is a create/write/delete (no more implicit guess, which would be a breaking change)


The choice is not that easy to make. If you have any argument in favor of one or another way of handling that I would be interestes in reading.


Once I have taken a decision, it shouldn't be long before I implement it, but for now you can't.
