### ISSUE TITLE
Documentation Explorer not working

### ISSUE THREAD

**Issue by PeterSchwarzHPI** [divad1196/odoo_graphql#21]
**Describe the bug**
When opening the GraphiQL docs, I got an error.
"Schema is invalid: Type Base must define one or more fields."

**To Reproduce**
1. Go to '<base_url>/graphiql'
2. Click on 'Show Documentation Explorer'

**Expected behavior**
Documentation Explorer is shown.

**Screenshots**
![](https://user-images.githubusercontent.com/1878447/236411133-cbfc5dfd-920f-4a79-b087-e3218dc6b3b2.png)

**Comment by divad1196** [comment]
@PeterSchwarzHPI once again thank you for your investment.

I will look at it as soon as possible.
Did you update the module recently?

**Comment by PeterSchwarzHPI** [comment]
@divad1196 updated the last time when we were talking about date/datetime.

**Comment by divad1196** [comment]
@PeterSchwarzHPI Thank you for the feedback.
I did a fix that work for me
https://github.com/divad1196/odoo_graphql/pull/22

Can you confirm it works on your side too?
I will inspect the query made by GraphiQl and use it as a unit test.

**Comment by PeterSchwarzHPI** [comment]
@divad1196 seems to work correctly now
