### ISSUE TITLE
Use with API-Key

### ISSUE THREAD

**Issue by swolf91** [divad1196/odoo_graphql#26]
Hello, I started using your odoo add-on to integrate odoo in a nextjs app. I just started using odoo and I'm still experimenting. so sorry if there's an obvious solution.

I followed your examples and everything works so far. But I wonder If I can use the API Key to access the graphql api instead of a session_id cookie? Is this possible?
When calling the json rpc api for authentication it only results the uid but not a session and afterwards the uid and the api key must be used in each authenticated request. So can this be used using your graphql endpoint as well? 

Thanks in advance.

**Comment by divad1196** [comment]
Hi and thank you for your interest.

This question not obvious so no worry.
I don't remember if I tested it with the API, but if the API key must be passed in an header, then it will simply work.

If the key must be passed as a password, then there is an option to pass the credentials (login/password) directly in the request. I cannot test it but it should work. Can you test it?

I will look at it when possible, it should be done by the end of the week at worst.

**Comment by swolf91** [comment]
Thank you that you want to have a look at it :) 

I already tested using the api key with the auth parameter in the body like shown here: https://github.com/divad1196/odoo_graphql/blob/14.0/odoo_graphql/examples/test_graphql2.py#L40-L43
It works to use the normal login and password. I substituted the password with the api key and it didn't work anymore. Then I substituted the login with the uid as well and it still didn't work unfortunately.

If there is a header that could be used (instead of the session_id cookie header) I don't know about it, but I tried to use the api-key as session_id cookie header and I tried to login like shown here https://github.com/divad1196/odoo_graphql/blob/14.0/odoo_graphql/examples/libs/graphql.js#L2-L33 and it didn't work as well. 

If I can do anything else, please let me know. 

Edit:

btw this is the json rpc call that works using the api key:

```http
POST http://localhost:8069/jsonrpc
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "id": null,
  "params": {
    "service": "common",
    "method": "login",
    "args": [
      "odoo",
      "email@example.com",
      "d81f1bf37fe70ea5c3cc4ac82b166d6cdbe679aa"
    ]
  }
}
```

args are db-name, login and api key in that order.

This call only returns the uid and in subsequent json rpc calls the uid and the api key must be passed. (Therefore I used the uid above as well)

**Comment by divad1196** [comment]
I was able to check that and I did a fix for the V16: https://github.com/divad1196/odoo_graphql/pull/28
I still need to backport that, document and add tests but you will be able to use it in V16 for now. I will try to backport that as soon as possible.

You have 2 ways of using the API Key:
1. Using the payload
    ```python
    payload = {
        "query": query,
        "auth": {
            "login": USER,
            "password": API_KEY
        },
    }
    res = requests.post(url, data=json.dumps(payload))
    ```
2. Using `Authorization: Basic ...` header
    ```python
    headers = {"Authorization": "Basic {}".format(
        base64.b64encode((USER + ":" + API_KEY).encode()).decode()
    )}
    payload = {"query": query}
    res = requests.post(url, headers=headers, data=json.dumps(payload))
    ```

**Comment by divad1196** [comment]
@swolf91 The backport is done, the change was the same and my test script ran perfectly on V14 and V15.
As said, I will still need to document it and integrate the tests correctly.
Nb: The modules on the Odoo app store won't be updated right away.

Can you confirm it is working now?

**Comment by swolf91** [comment]
That sounds great. Thank you very much. I'll give it a try tomorrow and report my results here. If you need some help with documenting, let me know

**Comment by swolf91** [comment]
I tested it using Odoo 16 and both versions work for me. I can use your auth body parameters and I can use the Authorization cookie like this:

```ts
return await fetch(`${this.baseUrl}/graphql`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/graphql',
                'Cookie': `${cookies.odooLanguage}=${this.locale.replace('-', '_')};`,
                'Authorization': `Basic ${Buffer.from(`${process.env.ODOO_LOGIN}:${process.env.ODOO_API_KEY}`).toString('base64')}`
            },
            body: JSON.stringify(body)
        })
```

Thank you very much for adding the feature that fast.
