### ISSUE TITLE
Set language over api

### ISSUE THREAD

**Issue by swolf91** [divad1196/odoo_graphql#27]
Hello, in the xml rpc api it's possible to set the language in which the entries are returned with a context lang parameter like shown here:

```
api.execute_kw(db, uid, pwd, 'res.country', 'search_read', [[]], {'fields': ['id', 'name'], 'context' :{'lang': "fr_FR"}})
```

(It's not tested by myself just found in the internet) 

I just want to know whether it's possible to set the language in which the entries are returned from your graphql api as well? Is there a header that can be set? 

I saw that odoo sets a `frontend_lang` cookie. I added the cookie to the request and changed the value to another language but it didn't work unfortunately. 

Thanks in advance for your help

**Comment by swolf91** [comment]
Please forget what I wrote above. it's not true. The language can be set using the `frontend_lang` cookie. I only saw the two languages in the database that were set up using Odoos demo data. But I didn't install the other language in odoo. Therefore I couldn't use it. Now I installed it and it just works. 
I hope you haven't had a look into this yet. Thank you

**Comment by divad1196** [comment]
Hi @swolf91,
I reopened the issue because, even if you are satisfied with your current answer, I think it would be legitimate to be able to ask for the language from the query itself.

I will take a look at it when possible and come back to you.

**Comment by divad1196** [comment]
Hi @swolf91,

I added a directive that allows you to change the `lang` value in the context
![image](https://github.com/divad1196/odoo_graphql/assets/43037556/8c598905-8eb4-4881-acce-7ea77c5a39fe)

You can use it at any level (query, Field, Fragment, ...) and it will be propagated to the underlying levels.
Let me know if it helps you and if it works correctly for you (available on 14.0, 15.0 and 16.0)

As for the other issue, I still need to document it.

**Comment by swolf91** [comment]
Hello, thank you very much. I like that. I gave it a try and what you tried above, works for me as well, but I found something that does not work as intended for me:

```gql
query getProductTemplates {
  GermanProductTemplates: ProductTemplate(limit: 2) @context(lang: "de_CH") {
    id
    display_name_en: display_name @context(lang: "en_US")
    display_name_de: display_name
    product_variant_ids @context(lang: "en_US") {
      display_name
    }
  }
  EnglishProductTemplates2: ProductTemplate(limit: 2) @context(lang: "en_US") {
    id
    display_name_en: display_name
    display_name_de: display_name @context(lang: "de_CH")
    product_variant_ids @context(lang: "de_CH") {
      display_name
    }
  }
}
```

In this query the context parameter works for the whole `ProductTemplate` and for the `product_variant_ids` but it does not work for the `display_name` field. 

Furthermore I noticed that this feature only works if you use the correct locale that is set in odoo (for me `en_US` and `de_CH`) but it does not work if you only pass the language (`de` or `en`) or if you pass a locale with the language but another country (`de_DE`). Instead it always returns kind of a default (for me English) even if the context from the level above was set to German. That's totally okay If you know it but I wanted to mention it because it works for the `frontend_lang` cookie. Using the cookie the language is also set correctly if only the language (without country - `de`) or the complete locale but for another country (`de_DE`) is passed.

--- 

My result for the query above:

```json
{
  "data": {
    "GermanProductTemplates": [
      {
        "id": 23,
        "display_name_en": "[FURN_6666] Akustische Blockbildschirme",
        "display_name_de": "[FURN_6666] Akustische Blockbildschirme",
        "product_variant_ids": [
          {
            "id": 31,
            "display_name": "[FURN_6666] Acoustic Bloc Screens"
          }
        ]
      },
      {
        "id": 9,
        "display_name_en": "Anpassbarer Schreibtisch",
        "display_name_de": "Anpassbarer Schreibtisch",
        "product_variant_ids": [
          {
            "id": 36,
            "display_name": "[DESK0005] Customizable Desk (Custom, White)"
          },
          {
            "id": 37,
            "display_name": "[DESK0006] Customizable Desk (Custom, Black)"
          },
          {
            "id": 12,
            "display_name": "[FURN_0096] Customizable Desk (Steel, White)"
          },
          {
            "id": 13,
            "display_name": "[FURN_0097] Customizable Desk (Steel, Black)"
          },
          {
            "id": 14,
            "display_name": "[FURN_0098] Customizable Desk (Aluminium, White)"
          }
        ]
      }
    ],
    "EnglishProductTemplates2": [
      {
        "id": 23,
        "display_name_en": "[FURN_6666] Acoustic Bloc Screens",
        "display_name_de": "[FURN_6666] Acoustic Bloc Screens",
        "product_variant_ids": [
          {
            "id": 31,
            "display_name": "[FURN_6666] Akustische Blockbildschirme"
          }
        ]
      },
      {
        "id": 15,
        "display_name_en": "[E-COM11] Cabinet with Doors",
        "display_name_de": "[E-COM11] Cabinet with Doors",
        "product_variant_ids": [
          {
            "id": 21,
            "display_name": "[E-COM11] Schrank mit Türen"
          }
        ]
      }
    ]
  }
}
```

**Comment by divad1196** [comment]
Hi, this is perfectly normal.
Odoo returns the values based on the context and a field itself doesn't have a context, only a record does.

It can only work on relation fields. I just don't think that I can make a distinction on the introspection.

Same for the code to use, Odoo isn't the first software to make this distinction. If you have multiple variants of your language you won't know which one to use. Therefore it is a bad idea to want it work with just "en", you should always be explicit when asking a language.

**Comment by swolf91** [comment]
I see, thanks for explaining. So the way to go would be to load the products twice as you did in your SaleOrder example and merge them afterwards I guess. The problem here is when using a domain to filter the results this could be different for different languages, so that the result might contain different results that are not mergeable. But I do not have a use case for this (at least not in my mind right now). For me it's good enough to specify the language on the top level and that works. Thank you :)

For me it's okay that the whole locale `de_CH` or `en_US` must be passed. I just wanted to make clear that this is NOT necessary when using the `frontend_lang` cookie to set the language. Here it's totally enough to only specify the language code. Additionally it works to specify a locale consisting of a language code and another country code that is not configured in odoo. So there's a difference in the way how they work and are processed.
I think that the code handling the frontend_lang cookie in odoo looks for the best fit in the configured locales.

**Comment by divad1196** [comment]
@swolf91 As you said, I don't see any scenarios where you would want only part of a record to be translated. If you ever need that, it is more likely that you have two different needs that must be resolved with two different requests. Most certainly, you won't need to merge their results at this point.


Also,, I have always seen the frontend_lang cookie being filled with the exact value:
![image](https://github.com/divad1196/odoo_graphql/assets/43037556/bbab8482-0a55-4ad0-a667-851b41c37894)
I don't know if it supports using `en` only. If it does, I assume that Odoo will then resend you the token with the correct value anyway (This is at least the behaviour observed on their website from the browser).

I would like to emphasis that the way an API shouldn't guess anything from the inputs it receives. One last thing is that Odoo has its own ORM that doesn't look alike any other ORM. This `@context(lang="...")` feature just take advantage of the `model.with_context(lang="...")` feature of the ORM. It means that anything that is supported by this module is supported as Odoo intended it.


Thank you for you feedback and I hope this module will be useful to you and others.
I am closing this issue now, have a nice day.
