### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Manuel1975** [divad1196/odoo_graphql#3]
Is it possible to integrate odoo and sambapos using GRAPHQL?
https://forum.sambapos.com/t/sambapos-erp-integration/8338/4
![9af74d9c62abd5eb40f32ae7fff329c542c3bbc5](https://user-images.githubusercontent.com/22622543/156703358-110713b2-cd95-4e97-846b-1a850e491996.jpg)

I hope you have a space, and talk about this project. Greetings.

**Comment by divad1196** [comment]
Hi @Manuel1975 ,
I am pleased that you are interested in this module, but I don't know sambapos.

My role is only to provide a graphql for Odoo. Whether it is what you need or how you would use it is up to you. 

All I can say is that you will certainly have to write code for that (write your queries and deal with authentication). You should see by sambapos' documentation to answer your question, not here.

Have a nice day.
