### ISSUE TITLE
Relations 1:N and N:N

### ISSUE THREAD

**Issue by hamicek** [divad1196/odoo_graphql#4]
Hello,
I tried using your addon to retrieve records, insert a simple record into contacts and update it. Everything worked seamlessly. The problem occurred when I wanted to enter a record into contacts that was bound to another table, namely `currency_id`, which has a 1:N binding to currency (your code generates its type to `ResCurrency`). I've tried a lot of ways to do this, but unfortunately it didn't work. It is very likely that I don't fully understand GraphQL, or I don't understand the linking with Odoo. Please would it be possible to put up some example of how this is used, specifically the 1:N and N:N bindings? I am attaching a piece of GraphQL to clarify my situation.

```graphql
mutation InsertResPartner {
	insertResPartner: ResPartner(
		vals: {
			active: true,
			active_contact: true,
			charging_postage: false,
			name: "Company 1",
			company_type: "company",
			cin: "09090909",
			city: "Pradejov",
			street: "Kosmicka 22",
			street2: "",
			zip: "12346",
			comment: "<p>bla bla bla</p>",
			phone: "",
			mobile: "777111222",
			number_of_client: "1212",
			vat: "CZ13243413",
			website: "http://xxx.cz",
			email: "nejaky@email.com",
			complete_contact: true,
			lang: "cs_CZ",
			employee: false,
			send_invoices_by_email: true,
			currency_id: 22
		}
	)
	{
		active
		active_contact
		charging_postage
		cin
		city
		comment
		company_type
		id
		name
		number_of_client
		vat
		phone
		mobile
		website
		email
		complete_contact
		lang
		street
		street2
		zip
		send_invoices_by_email
		currency_id
		employee
	}
}
```

Thank you very much for your reply.

**Comment by divad1196** [comment]
@hamicek  Hi, this is indeed related to currency_id.
Since it not an atomic data as string, int, ... but an object, you need to explicitly provide the fields you want to retrieve.
The server response is not good, instead of throwing an error I will consider it implicitly as if you wanted to retrieve only the ID.

The patch is done on both version (14.0 and 15.0) if you dare download it and confirm it working for you? 
But to make it clear: you should explicitly use 
```
currency_id {
    id
}
```
And not just "currency_id"

**Comment by hamicek** [comment]
Thank you very much for the answer, I tried it with 1:N binding and it works fine. Have a nice day.

**Comment by divad1196** [comment]
@hamicek No problem, thank you too for reporting it so I can improve the module.
I would be grateful if you would mark the module on the store and/or leave a comment.
Have a nice day.

**Comment by hamicek** [comment]
I already commented on the module in the shop, I gave you a high rating, it's a tek comment on the name Halabrin :-)

> 11. 4. 2022 v 19:56, divad1196 ***@***.***>:
> 
> No problem, thank you too for reporting it so I can improve the module.
> I would be grateful if you would mark the module on the store and/or leave a comment.
> Have a nice day.
