### ISSUE TITLE
How do we query the data specific to multiple filter  parameter using domain tuple

### ISSUE THREAD

**Issue by rs21k** [divad1196/odoo_graphql#6]
The expected format of Tuple in domain is [("id","=",1)] from odoo but when we try below query it fails with validation error and there is no example of domain in the tests or document
```
query GetUserInfo {
    Users(domain:[("id","=",1)]){
    id
    name
    country
    age
    }
  }
```

**Comment by divad1196** [comment]
@ersandeepranjit 
You have not read graphql documentation nor looked at the examples.
Graphql does not know what "( ,)" (tuple in python) is. You have to use list instead.
domain: [ [ "id", "=", 1 ], ... ]

Additionnaly, you have it wrong: Odoo does not expect a tuple in particular, a list does the work and is often used by Odoo itself (e.g. from javascript, rpc, or even directly in the code). Tuples are just more performant (and are more visible).

Also, the user table is not "users" in Odoo, this won't work. You have to use the correct model name which is derived from the Odoo model's name.

Please, be sure to read graphql documentation, the Readme of the repository and check the examples provided before asking your questions.

**Comment by divad1196** [comment]
@ersandeepranjit 
Please, avoid editing you initial message and write new comments once I responded.

For the examples, you have one in thr html example.
```javascript
                    products: ProductTemplate(domain: [["name", "ilike", $name]]) {
```

I will maybe make it clearer in the futur for those that don't read, but everything is in the examples, I will not make all examples for each languages.
